application: juicetestapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /receiver/css
  static_dir: /receiver/css

- url: /rcvr/receiver.html
  static_files: rcvr/receiver.html
  upload: rcvr/receiver.html
